### ISSUE TITLE
Requirement for Storage Grid discovery - does not really apply as seen with both customer system and lab test.

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/bluexp-storagegrid#17]
### Page URL

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html

### Page title

Discover StorageGRID systems

### Summary

Requirement for Storage Grid discovery - does not really apply as seen with both customer system and lab test.
Customers are renting storage grid and they are not provided with credentials for Storage Grid discovery except for a specific user accesskey for a tenant on Storage Grid to be used for Cloud Backup Service.

Just a note that Discovery is not mandatory would also do.
Lab test seen to work without discovery of storage grid.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thanks, Anee. Let's discuss more over chat.

**Comment by netapp-bcammett** [comment]
Closing after discussing over chat.
